// Generated by gencpp from file coatimunde/PointCoords.msg
// DO NOT EDIT!


#ifndef COATIMUNDE_MESSAGE_POINTCOORDS_H
#define COATIMUNDE_MESSAGE_POINTCOORDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coatimunde
{
template <class ContainerAllocator>
struct PointCoords_
{
  typedef PointCoords_<ContainerAllocator> Type;

  PointCoords_()
    : x(0)
    , y(0)  {
    }
  PointCoords_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::coatimunde::PointCoords_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coatimunde::PointCoords_<ContainerAllocator> const> ConstPtr;

}; // struct PointCoords_

typedef ::coatimunde::PointCoords_<std::allocator<void> > PointCoords;

typedef boost::shared_ptr< ::coatimunde::PointCoords > PointCoordsPtr;
typedef boost::shared_ptr< ::coatimunde::PointCoords const> PointCoordsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coatimunde::PointCoords_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coatimunde::PointCoords_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coatimunde

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'coatimunde': ['/home/t/coatimunde/catkin_ws/src/coatimunde/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coatimunde::PointCoords_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coatimunde::PointCoords_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coatimunde::PointCoords_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coatimunde::PointCoords_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coatimunde::PointCoords_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coatimunde::PointCoords_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coatimunde::PointCoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd7b43fd41d4c47bf5c703cc7d016709";
  }

  static const char* value(const ::coatimunde::PointCoords_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd7b43fd41d4c47bULL;
  static const uint64_t static_value2 = 0xf5c703cc7d016709ULL;
};

template<class ContainerAllocator>
struct DataType< ::coatimunde::PointCoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coatimunde/PointCoords";
  }

  static const char* value(const ::coatimunde::PointCoords_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coatimunde::PointCoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
";
  }

  static const char* value(const ::coatimunde::PointCoords_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coatimunde::PointCoords_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointCoords_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coatimunde::PointCoords_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coatimunde::PointCoords_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COATIMUNDE_MESSAGE_POINTCOORDS_H
